source 'https://rubygems.org'

gem 'chefspec', '~> 3.4.0'
gem 'rspec', '~> 2.14.0'
gem 'rspec-core', '~> 2.14.0'
gem 'rspec-expectations', '~> 2.14.0'
gem 'rspec-mocks', '~> 2.14.0'
gem 'chef', '~> 11.8'
gem 'foodcritic', '~> 3.0.0'
gem 'daptiv-foodcritic-rules'
gem 'tailor'
gem 'rake'
gem 'berkshelf', '~> 3.1.5'
gem 'minitest-chef-handler'
gem 'daptiv-chef-ci', '~> 0.0.14'
gem 'chef-sugar', '~> 2.0.0'