source 'https://rubygems.org'

gem 'berkshelf'
gem 'chef-sugar'
gem 'chefspec'
gem 'foodcritic'
gem 'minitest-chef-handler'
gem 'rake'
gem 'rspec-mocks'
gem 'rspec'
gem 'rspec-core'
gem 'rspec-expectations'
gem 'rubocop'
