variable "ami_name" {}
variable "ami_owners" {}
variable "bastion_host" {}
variable "bastion_user" {}
variable "config_volume_ids" {}
variable "data_volume_ids" {}
variable "domain_name" {}
variable "env_hostname_prefix" {}
variable "instance_count" {}
variable "instance_iam_instance_profile" {}
variable "instance_key_name" {}
variable "instance_private_key" {}
variable "instance_security_group_ids" {}
variable "instance_subnet_ids" {}
variable "instance_type" {}
variable "instance_user" {}
variable "load_balancer" {}
variable "log_volume_ids" {}
variable "remote_state_region" {}
variable "service_name" {}
