variable "ami_name" {}
variable "ami_owners" {}
variable "bastion_host" {}
variable "bastion_user" {}
variable "chef_config_dir" {}
variable "chef_environment" {}
variable "chef_server_url" {}
variable "chef_user_name" {}
variable "chef_version" {}
variable "docker_volume_ids" {}
variable "domain_name" {}
variable "env_hostname_prefix" {}
variable "hostname_identifier" {}
variable "instance_count" {}
variable "instance_iam_instance_profile" {}
variable "instance_key_name" {}
variable "instance_private_key" {}
variable "instance_security_group_ids" {}
variable "instance_subnet_ids" {}
variable "instance_type" {}
variable "instance_user" {}
variable "logs_volume_ids" {}
variable "remote_state_region" {}
variable "secret_key_file" {}
variable "service_name" {}
variable "user_key_file" {}
variable "work_volume_ids" {}
